---
# DNS Infrastructure Role - Main Tasks
# Provisions LXC containers and installs DNS software (BIND9 + Pi-hole)

- name: Include variable definitions
  include_vars: "{{ ansible_os_family }}.yml"
  failed_when: false

- name: Create LXC containers for DNS services
  include_tasks: lxc-containers.yml
  tags:
    - lxc
    - containers

- name: Install and configure BIND9
  include_tasks: bind9-install.yml
  tags:
    - bind9
    - dns-server

- name: Install and configure Pi-hole
  include_tasks: pihole-install.yml
  tags:
    - pihole
    - dns-filter

- name: Configure networking and firewall
  include_tasks: networking.yml
  tags:
    - networking
    - firewall

- name: Verify DNS services
  include_tasks: verification.yml
  tags:
    - verify
    - test