#cloud-config

# Minimal SSH fix for Proxmox VMs
ssh_pwauth: false
disable_root: true

# Ensure SSH is enabled and running
runcmd:
  # Start and enable SSH service
  - systemctl enable --now ssh
  
  # Basic SSH security configuration
  - |
    if ! grep -q "PermitRootLogin no" /etc/ssh/sshd_config; then
      echo "PermitRootLogin no" >> /etc/ssh/sshd_config
    fi
  - |
    if ! grep -q "PubkeyAuthentication yes" /etc/ssh/sshd_config; then
      echo "PubkeyAuthentication yes" >> /etc/ssh/sshd_config
    fi
  
  # Disable firewall temporarily for testing
  - systemctl disable --now ufw || true
  
  # Restart SSH with new config
  - systemctl restart ssh
  
  # Fix SSH directory permissions
  - chmod 700 /home/ubuntu/.ssh || true
  - chmod 600 /home/ubuntu/.ssh/authorized_keys || true
  - chown -R ubuntu:ubuntu /home/ubuntu/.ssh || true

# Ensure openssh-server is installed
packages:
  - openssh-server

final_message: "SSH should now be accessible"