---
# System Updates and Maintenance playbook for VUV Lab Infrastructure
# Performs system package updates, maintenance tasks, and security configurations

- name: System Updates and Maintenance
  hosts: all
  gather_facts: yes
  become: yes
  
  vars:
    essential_packages:
      - htop
      - git
      - vim
      - curl
      - wget
      - tree
      - unzip
      - net-tools
      - dnsutils
      - tcpdump
      - rsync
      - screen
      - tmux
      - nano
      - less
      - jq
      - systemd-timesyncd
      - update-notifier-common
      
  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes
        cache_valid_time: 3600
        
    - name: Upgrade all packages
      apt:
        upgrade: dist
        autoremove: yes
        autoclean: yes
      register: upgrade_result
      
    - name: Display upgrade summary
      debug:
        msg: |
          Packages upgraded: {{ upgrade_result.changed }}
          {% if upgrade_result.changed %}
          Reboot required: {{ ansible_reboot_pending | default(false) }}
          {% endif %}
          
    - name: Install essential packages
      apt:
        name: "{{ essential_packages }}"
        state: present
        
    - name: Install unattended-upgrades for automatic security updates
      apt:
        name:
          - unattended-upgrades
          - apt-listchanges
        state: present
        
    - name: Configure unattended-upgrades for security updates only
      copy:
        dest: /etc/apt/apt.conf.d/50unattended-upgrades
        content: |
          Unattended-Upgrade::Allowed-Origins {
              "${distro_id}:${distro_codename}-security";
              "${distro_id} ESMApps:${distro_codename}-apps-security";
              "${distro_id} ESM:${distro_codename}-infra-security";
          };
          Unattended-Upgrade::Remove-Unused-Kernel-Packages "true";
          Unattended-Upgrade::Remove-New-Unused-Dependencies "true";
          Unattended-Upgrade::Remove-Unused-Dependencies "true";
          Unattended-Upgrade::Automatic-Reboot "false";
          Unattended-Upgrade::Automatic-Reboot-WithUsers "false";
          Unattended-Upgrade::Mail "root";
        owner: root
        group: root
        mode: '0644'
        backup: yes
        
    - name: Configure automatic security updates schedule
      copy:
        dest: /etc/apt/apt.conf.d/20auto-upgrades
        content: |
          APT::Periodic::Update-Package-Lists "1";
          APT::Periodic::Unattended-Upgrade "1";
          APT::Periodic::Download-Upgradeable-Packages "1";
          APT::Periodic::AutocleanInterval "7";
        owner: root
        group: root
        mode: '0644'
        backup: yes
      notify: restart unattended-upgrades
      
    - name: Ensure unattended-upgrades service is running
      systemd:
        name: unattended-upgrades
        state: started
        enabled: yes
        
    - name: Enable and start systemd-timesyncd for time synchronization
      systemd:
        name: systemd-timesyncd
        enabled: yes
        state: started
        
    - name: Clean package cache and remove unused packages
      apt:
        autoclean: yes
        autoremove: yes
        
    - name: Check if reboot is required
      stat:
        path: /var/run/reboot-required
      register: reboot_required
      
    - name: Get system information after updates
      command: "{{ item }}"
      register: system_info
      changed_when: false
      loop:
        - "uname -r"
        - "uptime"
        - "df -h /"
        
          
    - name: Warning about pending reboot
      debug:
        msg: |
          ⚠️  ATTENTION: {{ inventory_hostname }} requires a reboot to complete updates!
          Connect to the host and run: sudo reboot
      when: reboot_required.stat.exists
      
  handlers:
    - name: restart unattended-upgrades
      systemd:
        name: unattended-upgrades
        state: restarted